googleapis/python-pubsub

google/cloud/pubsub_v1/publisher/_batch/base.py
google/cloud/pubsub_v1/publisher/_batch/thread.py
google/cloud/pubsub_v1/publisher/_sequencer/base.py
google/cloud/pubsub_v1/publisher/_sequencer/ordered_sequencer.py
google/cloud/pubsub_v1/publisher/_sequencer/unordered_sequencer.py
google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/publisher/exceptions.py
google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
google/cloud/pubsub_v1/subscriber/_protocol/messages_on_hold.py
google/cloud/pubsub_v1/subscriber/_protocol/requests.py
google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
google/cloud/pubsub_v1/subscriber/message.py
google/cloud/pubsub_v1/types.py
tests/unit/pubsub_v1/publisher/batch/test_base.py
tests/unit/pubsub_v1/publisher/batch/test_thread.py
tests/unit/pubsub_v1/publisher/sequencer/test_ordered_sequencer.py
tests/unit/pubsub_v1/publisher/sequencer/test_unordered_sequencer.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_dispatcher.py
tests/unit/pubsub_v1/subscriber/test_leaser.py
tests/unit/pubsub_v1/subscriber/test_message.py
tests/unit/pubsub_v1/subscriber/test_messages_on_hold.py
tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

feat(pubsub): ordering keys

---

google/cloud/pubsub_v1/subscriber/client.py
noxfile.py
tests/system.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

Fixes #4.
This PR gives users a more handy way of closing the subscriber's underlying channel.
-  Make sure that a topic has a few messages published to it to avoid the issue with a dubious `DeadlineExceeded` response.
- List the currently open sockets by Python:
```
$ lsof -i -n | grep python
```
- Run the code snippet from the ticket description in debugger, but by using the subscriber client as a context manager:
```py
with subscriber:
...
```
Make sure to place a breakpoint after the `with` block.
- After the messages have been pulled and the context manager exited, list the open sockets again.
**Actual result (before the fix):**
Subscriber client cannot be used as a context manager. Using it without the context results in open sockets being leaked until the Python process terminates, …

feat: add context manager capability to subscriber

---

tests/system.py

Fixes #8.
This PR adds several system tests focusing on RBAC.
I used all non-admin [PubSub roles](https://cloud.google.com/pubsub/docs/access-control#roles) in common happy use cases. If there are other uses cases that should also be added, feel free to suggest in the comments.

test: add system tests for common RBAC operations

---

google/cloud/pubsub_v1/subscriber/futures.py
tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py

Fixes #39.
This PR fixes an error that can happen if cancelling a streaming pull future when the streaming pull manager has already been shut down due to the error in the user callback.
- Have a topic and a subscription, publish at least one message to the topic.
- Take the basic [streaming pull sample](https://cloud.google.com/pubsub/docs/pull#asynchronous-pull) from the docs.
- Adjust the message received callback to raise an exception
**Actual result (before the fix):**
An error occurs during the shutdown:
```
RuntimeError: set_result can only be called once.
```
**Expected result (after the fix):**
No internal error occurs during the shutdown, except for the error from the user callback, as expected.

fix: shutdown error on streaming pull callback error

---

google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
google/cloud/pubsub_v1/types.py
tests/unit/pubsub_v1/subscriber/test_leaser.py
tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

feat(pubsub): implement max_duration_per_lease_extension option

---

CHANGELOG.md

Context: https://github.com/googleapis/python-spanner/issues/28
Edit: Fixes #45.

fix: fix changelog links to point to issues in the old repo.

---

google/cloud/pubsub_v1/publisher/_batch/thread.py
google/cloud/pubsub_v1/publisher/_sequencer/unordered_sequencer.py
tests/unit/pubsub_v1/publisher/sequencer/test_unordered_sequencer.py

Unordered batches that threw errors on invoking the publish RPC led to subsequent assertion failures in thread.py::publish(). These assertion failures were legitimate. Publish calls should not be called on batches that have already been committed. (In this case, they were committed and then returned an error.)
This pull request fixes the underlying issue by clearing out the UnorderedSequencer's _current_batch on commit(). This ensures that no subsequent publish() calls will be called on that batch since the reference to it is lost.
I add a new "test_publish_after_batch_error" test for this scenario.
The OrderedSequencer does not have this issue. On error, it cancels all batches and pauses the ordering key. The existing "test_batch_done_unsuccessfully" test captures this scenario.
Fixes …

fix: don't assert on unordered publishes after publish error

---

google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/subscriber/client.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

- The client_options.api-endpoint parameter was being ignored. This bug prevented users from using regional endpoints. It also made it harder to test code against nonprod endpoints.
Fixes #61

fix: use client_options.api_endpoint parameter instead of ignoring it

---

CHANGELOG.md
docs/conf.py
docs/subscriber/api/message.rst
docs/types.rst

Fixes #69.
This PR fixes the docs generation warnings that occur in the latest version of Sphinx, causing the builds to fail (we treat warnings as errors).
To test the PR, generate the docs with and without the changes here. With the changes, the docs build should not fail anymore, while the docs themselves are not changed (apart from the changelog that had some structural issues).
PR checklist:

fix: fix docs warnings in Sphinx 3.0+

---

setup.py

Fixes #74 
Fixes #75.
The `google-api-core` version 1.17.0 released yesterday causes problems on re-establishing message streams on retryable errors, thus restricting it.
To test, make a fresh installation of the the pubsub client with and without this version pin change, and try to reproduce the issue as described.
Tip: Deadline Exceeded errors can be triggered by temporarily disable internet connection on the local machine, and then re-enable it to see if the stream is re-established.

fix: restrict api-core dependency to < 1.17.0

---

google/cloud/pubsub_v1/subscriber/message.py

fix: remove EXPERIMENTAL notice for DLQ b/c it's GA now 

---

google/cloud/pubsub_v1/subscriber/client.py
google/cloud/pubsub_v1/subscriber/scheduler.py

docs: clarify that Schedulers shouldn't be used with multiple SubscriberClients

---

google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/publisher/exceptions.py
google/cloud/pubsub_v1/publisher/flow_controller.py
google/cloud/pubsub_v1/types.py
tests/unit/pubsub_v1/publisher/test_flow_controller.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py

Closes #16.
Closes #72.
This PR adds flow control settings to publisher client, similar to what was [added](https://github.com/googleapis/java-pubsub/pull/119) to the Java client recently.
The PR does not interfere with existing publish logic (sequencers, ordering keys, batching...). Instead, it acts like a valve placed in front of the publish pipeline, and taking the configured action if it detects excessive message flow.

feat: add flow control for message publishing

---

google/cloud/pubsub_v1/gapic/publisher_client.py
google/cloud/pubsub_v1/gapic/subscriber_client.py
synth.py

Fixes #110.
This PR fixes two samples in subscriber docstrings. Ideally, this should be addressed in the code generator itself, but until then we can fix this manually on the PubSub side.
I did not re-generate all files due to the current issue with docstring format, thus the PR only includes the relevant changes in the generated code.

docs: fix update subscription/snapshot/topic samples

---

docs/subscriber/index.rst

Closes #122.
This PR adds a short explanation on how to NACK sync pull messages.

docs: explain how to nack a sync pull message

---

samples/snippets/subscriber.py

The white space is causing the sample not to be found.

samples: remove extra white space in region tag

---

samples/snippets/README.rst
samples/snippets/publisher.py
samples/snippets/publisher_test.py
samples/snippets/subscriber.py
samples/snippets/subscriber_test.py

Add samples for publish with ordering keys. The test can't be run yet because the feature isn't released:

samples: publish with ordering keys

---

tests/unit/pubsub_v1/publisher/test_publisher_client.py

Fixes #178.
Patching the client under test should be done on an instance used in a test, not on the instance's class - patching the latter can cause all other instances of the same class to share the patched method, possibly interfering with the patched method's call count.
This can probably be shipped along the new major version, as it does not interfere with the changes made there.

test: fix flaky sequencer unit tests

---

google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/subscriber/client.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

fix: pass client options to publisher and subscriber clients (#166)

---

docs/subscriber/index.rst

docs: use new call syntax in subscriber docs

---

docs/subscriber/index.rst

docs: fix get topic_path in subscriber sample

---

samples/snippets/publisher.py
samples/snippets/subscriber.py
samples/snippets/subscriber_test.py

Clarify that the defaults in publisher sample are not defaults that come with the [`google.api_core.retry.Retry`](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry) object.
They are set by the library [here](https://github.com/googleapis/python-pubsub/blob/b64e2187ab0810437575580d6ddb5315ff60e274/google/pubsub_v1/services/publisher/transports/base.py#L135-L151) via [`pubsub_grpc_service_config.json`](https://github.com/googleapis/googleapis/blob/3a935fab757e09c72afd4aa121147a4c97dccc3e/google/pubsub/v1/pubsub_grpc_service_config.json#L42-L62). You can see that the default timeout=60s instead of 600s. 
Also fixed a few things in subscriber samples and tests. Main fixes:
- The pytest fixture for dead letter subscription needs to be created with an …

samples: clarify comments in samples

---

samples/snippets/subscriber.py
samples/snippets/subscriber_test.py

Add optional max_delivery_attempts argument to sample code to more closely resemble Cloud Pub/Sub behavior.
Fixes #235  🦕

feat: Add dead lettering max delivery attempts argument

---

samples/snippets/noxfile_config.py

Use a separate project per sample test session. This file `noxfile_config.py` was copied from https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#noxfile_configpy
Fixes #240 
Fixes #246 
Fixes #227

chore: add noxfile_config to samples dir

---

google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/subscriber/client.py

fix: pass anonymous credentials for emulator

---

samples/snippets/noxfile_config.py
samples/snippets/subscriber_test.py

Fixes #240
Fixes #227 
Fixes #246
I can add type hints in samples (#264) and turn on this check in Q1 2021. Setting it to true would cause a lot of lint failures. 
Fixes flaky tests that complain about `subscription not found`.

fix: flaky samples tests

---

google/pubsub_v1/services/publisher/async_client.py
google/pubsub_v1/services/publisher/client.py
google/pubsub_v1/services/publisher/transports/base.py
google/pubsub_v1/services/schema_service/async_client.py
google/pubsub_v1/services/schema_service/client.py
google/pubsub_v1/services/schema_service/transports/base.py
google/pubsub_v1/services/subscriber/async_client.py
google/pubsub_v1/services/subscriber/client.py
google/pubsub_v1/services/subscriber/transports/base.py
synth.metadata
synth.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

Fixes #200.
This PR patches the generated code so that client library version is actually included in the `x-goog-api-client` metrics key.
PR checlist:

fix: client version missing from the user agent header

---

google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
google/cloud/pubsub_v1/subscriber/_protocol/heartbeater.py
google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
google/cloud/pubsub_v1/subscriber/futures.py
google/cloud/pubsub_v1/subscriber/scheduler.py
tests/system.py
tests/unit/pubsub_v1/subscriber/test_dispatcher.py
tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
tests/unit/pubsub_v1/subscriber/test_heartbeater.py
tests/unit/pubsub_v1/subscriber/test_leaser.py
tests/unit/pubsub_v1/subscriber/test_scheduler.py
tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Closes #276.
This PR implements an optional blocking streaming pull shutdown. "Blocking" means  blocking on `streaming_future.cancel()` until all currently executing user callbacks complete, as well as dispatching any message ACK or NACK requests these callbacks produce.
The PR also makes sure that any received messages sitting in internal queues - but not yet dispatched to the callbacks - are automatically NACK-ed on shutdown to speed up their re-delivery (the backend is not left waiting for their ACK deadlines to expire).
PR checklist:

feat: add graceful streaming pull shutdown

---

samples/snippets/quickstart/quickstart_test.py
samples/snippets/requirements-test.txt
samples/snippets/subscriber_test.py

Using a solution proposed in go/handling-flakes (internal doc) by @tmatsuo 
Fixes #291 
Fixes #289 
Fixes #288 
Fixes #246 
Fixes #227

samples: use flaky in tests

---

samples/snippets/subscriber_test.py

fixes #289
fixes #288
I think there were few problems with the tests.
1. google.api_core.exceptions.Unknown is not retried.
2. number of messages published in test_receive_synchronously_with_lease
was 5, but the sample code is fetching 3 messages in bulk.
3. assertion in test_receive_synchronously_with_lease was too strict.
4. failure in subscriber_test was incorrectly considered a failure in
teardown of quickstart_test.
I hope these changes will mitigate the flakiness.

fix(sample): mitigate flakiness in subscriber_test

---

samples/snippets/subscriber_test.py

fix(sample): bump the max_time to 10 mins for a flaky test

---

samples/snippets/requirements.txt

Release 2.4.0 has been yanked from PyPi: https://pypi.org/project/google-cloud-pubsub/

samples: downgrade lib version in requirements.txt for samples testing

---

samples/snippets/subscriber_test.py

fix(sample): mark test flaky

---

samples/snippets/subscriber_test.py

fix(sample): retry InternalServerError

---

CHANGELOG.md
setup.py

This is a release PR with polished release notes (supersedes #346).

chore: release 2.4.1

---

google/pubsub_v1/services/subscriber/async_client.py
google/pubsub_v1/services/subscriber/client.py
synth.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

Closes #350.
This PR patches the generated client to emit a DeprecationWarning if `return_immediately` flag is set.
**PR checklist**

chore: emit a warning if return_immediately flag is set with synchronous pull

---

README.rst

docs: fix `create_topic()` call in README

---

tests/unit/pubsub_v1/conftest.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py

chore: pass explicit credentials in all unit tests creating clients

---

.coveragerc
google/cloud/pubsub_v1/publisher/_batch/base.py
google/cloud/pubsub_v1/publisher/_sequencer/base.py
google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/publisher/flow_controller.py
google/cloud/pubsub_v1/subscriber/scheduler.py
synth.py
tests/unit/gapic/pubsub_v1/test_subscriber.py
tests/unit/pubsub_v1/publisher/batch/test_base.py
tests/unit/pubsub_v1/publisher/batch/test_thread.py
tests/unit/pubsub_v1/publisher/sequencer/test_unordered_sequencer.py
tests/unit/pubsub_v1/publisher/test_flow_controller.py
tests/unit/pubsub_v1/publisher/test_publisher_client.py
tests/unit/pubsub_v1/subscriber/test_message.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
tests/unit/pubsub_v1/test__gapic.py

Closes #363.
Closes #367.
This PR fixes the code lines/paths that currently drag the overall coverage down.
The majority are error code paths in tests that are never executed if a test passes, and abstract methods that we do not explicitly test if they indeed raise `NotImplementedError`. The rest is some unused code and a few other misc. cleanups.

chore: bump test coverage to 100%

---

google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Fixes #352.
Fixes #373.
This PR fixes unit test flakiness by waiting for the streaming pull manager shutdown thread to finish running before making any assertions.
**PR checklist**

chore: fix streaming pull close test flakiness

---

tests/system.py

Fixes #372.
If a test is run in a suite with other system tests, the messages are not always published in batch sizes as desired, which can affect how ACKs are handled on the backend (the server requires all messages published in a single batch to be ACK-ed in order
to accept the ACKs).
If a publisher client instance is shared between the tests, the batching can apparently be affected, thus we create a new client
instance before each test. Since these tests are slow system tests, the overhead should not be significant.
Apply the following patch to the code, disable capturing test output (`-s` option to the `py.test` command).
```patch
diff --git google/cloud/pubsub_v1/publisher/_batch/thread.py google/cloud/pubsub_v1/publisher/_batch/thread.py
index 36dd3b9..c3aacdf 100644
--- …
```

test: fix flaky test for blocking pull shutdown

---

google/cloud/pubsub_v1/publisher/client.py
google/cloud/pubsub_v1/subscriber/client.py

In the case where a user is not running from within a pip package, the google-cloud-pubsub distribution might not be available. At the moment this will cause a fatal DistributionNotFound error because in the publisher and subscriber client, we try to extract the distribution version using 'pkg_resources.get_distribution("google-cloud-pubsub").version'.
In the case where a distribution is not found, making the change to set the version to 0.0.

fix: do not crash if distribution cannot be found when extracting semver

---

google/cloud/pubsub_v1/publisher/_batch/thread.py
google/cloud/pubsub_v1/publisher/client.py

Fixes #395.
If publish threads are marked as daemonic, the leak seemingly disappears.
Set up a topic and a subscription, install `memoryprofiler`. Add the `@profile` decorator to the `main()` function from the [sample code](https://github.com/googleapis/python-pubsub/issues/395#issuecomment-829263348) and run it (with and without the fix):
```
$ mprof run sample.py
```
After each run, plot the memory usage graph:
```
$ mprof plot
```
The graphs should look similar to the ones posted [here](https://github.com/googleapis/python-pubsub/issues/395#issuecomment-829910303).

fix: memory leak when publishing messages

---

google/cloud/pubsub_v1/futures.py
google/cloud/pubsub_v1/publisher/_batch/thread.py
google/cloud/pubsub_v1/publisher/futures.py
google/cloud/pubsub_v1/subscriber/futures.py
tests/unit/pubsub_v1/publisher/test_futures_publisher.py
tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
tests/unit/pubsub_v1/test_futures.py

Closes #368.
Possibly supersedes #374.
This is a different approach to the same feature request which does not rely on implementation details of `concurrent.futures.Future` (as discussed offline). Instead, the custom base `Future` implementation is _replaced_ with the one from `concurrent.futures` package with only minor adjustments to fit specific needs of publisher/subscriber futures.
The interface stays the same, and the `isinstance()` checks should keep working, as `concurrent.futures.Future` is injected is injected into the right place in MRO.
**PR checklist**

feat: make publish futures compatible with concurrent.futures.as_completed()

---

google/cloud/pubsub_v1/subscriber/scheduler.py
tests/unit/pubsub_v1/subscriber/test_scheduler.py

Fixes #394 (possibly).
This PR fixes uncaught exceptions in internal `scheduler` that can happen when the underlying executor is already being shut down (by another thread). It might not fix the reported hanging behavior, but it's a start.

fix: scheduler errors when executor in shutdown

---

google/cloud/pubsub_v1/subscriber/_protocol/histogram.py
google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
google/cloud/pubsub_v1/types.py
tests/unit/pubsub_v1/subscriber/test_histogram.py
tests/unit/pubsub_v1/subscriber/test_leaser.py
tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py

Fixes #413.
This PR makes sure that the ACK deadline set for the received messages is always consistent with what the leaser uses internally when extending the ACK deadlines for the leased messages.
See the issue description and a [comment](https://github.com/googleapis/python-pubsub/issues/413#issuecomment-844995852) explaining a possible sequence of events that lead to a bug.
**PR checklist**

fix: ACK deadline set for received messages can be too low 

---

google/cloud/pubsub_v1/subscriber/futures.py

docs: explain that future.cancel() is non-blocking

---

.github/sync-repo-settings.yaml
.kokoro/presubmit-against-pubsublite-samples.sh
.kokoro/presubmit/common.cfg
.kokoro/presubmit/presubmit-against-pubsublite-samples.cfg
.kokoro/presubmit/presubmit.cfg

Add a presubmit test to run against samples in https://github.com/googleapis/python-pubsublite.
This is to prevent future development here from breaking `python-pubsublite` unknowingly, which has happened before in version 2.4.0: https://pypi.org/project/google-cloud-pubsub/#history
Hard-coded `pytest` code instead of using `nox`.

test: presubmit against Lite samples

---

google/cloud/pubsub_v1/subscriber/client.py
samples/snippets/quickstart/sub.py
samples/snippets/schema.py
samples/snippets/subscriber.py

Fixes #423.
If subscriber client is used as a context manager, we need to block until the shutdown is complete before leaving the `with` block. See the issue description for more details.

docs: block until the streaming pull shuts down

---

.kokoro/presubmit-against-pubsublite-samples.sh

As @plamut rightly pointed out, `EXIT=$` needs to be placed right after `pytest`. 
https://github.com/googleapis/python-pubsub/pull/425#discussion_r650695456

test: gather status code after pytest

---

google/cloud/pubsub_v1/publisher/flow_controller.py
tests/unit/pubsub_v1/publisher/test_flow_controller.py

Fixes #421.
Contrary to the bytes reservations, free message slots are not distributed in FIFO order among the waiting threads, meaning that a message arriving later could be accepted before a message already waiting in the queue.
This PR fixes it by enforcing FIFO distribution of available message slots + some simplifications of the logic and data structures.
**Tip:** Might be easier to review commit-by-commit, each contains a well-rounded change to the codebase.

fix: threads can skip the line in publisher flow controller

---

samples/snippets/publisher.py

Address @kamalaboulhosn 's comments in #717
The goal of the sample `pubsub_publish_with_error_handler` is to show how to handle publish failures. In the current iteration, I want to show how to catch and handle `TimeoutError`. I know using a generic exception isn't generally recommended by samples rubrics. Let me know if you see a better type of error to catch in this sample.

samples: publish with error handler and flow control

---

samples/snippets/schema_test.py
samples/snippets/subscriber.py
samples/snippets/subscriber_test.py

Fixes #430. (maybe)
I was not able to reproduce flakiness locally, thus this PR is a best guess.
The test failure suggests that more than three messages were received, even though we only publish 3 messages in the test. This could be due to message re-delivery or because a topic might be shared between tests.
This PR reduces the total wait time in the message callback. It used to be 5 + 5 seconds, which is just the default ACK deadline, thus reducing that to 8 seconds might help. In addition, the test now prints the log output if one of the assertions fail, which will help with debugging, should the flakiness continue.
We could also use auto retries by `flaky` as a last resort, but let's see if we can fix the root cause first.
(**update:** Yet I did this for the unrelated delete schema …

tests: mitigate flaky snippets tests

---

samples/snippets/subscriber_test.py

Fixes #341 🦕
The stream sometimes gets removed (`UNKNOWN` errors) before the subscriber can successfully pull messages. Pausing to give the subscriber some time to reconnect since this subscription (`subscription_sync`) is used in two different synchronous pull samples:
- test_receive_synchronously_with_lease
- test_receive_synchronously
If this doesn't fix the flaky test, I will consider using two different subscriptions for the two different sync pull samples tests.
The delete schema sample test failure is unrelated. It's known and is flaky due to backend issues.

samples(test): flaky sync pull test

---

setup.py
testing/constraints-3.6.txt

Fixes #414.
See the issue [comment](https://github.com/googleapis/python-pubsub/issues/414#issuecomment-856452925) for more info.

fix: require grpcio >= 1.38.1 to prevent a possible crash

---

docs/publisher/api/pagers.rst
docs/publisher/index.rst
docs/subscriber/api/pagers.rst
docs/subscriber/index.rst

Fixes #436.
This PR makes sure that the docs for `*Pager` classes are generated and cross-linked in the docs for methods that return them.

docs: include docs for Pager classes

---

setup.py

Expand pins on library dependencies in preparation for these dependencies taking a new major version. See https://github.com/googleapis/google-cloud-python/issues/10566.

chore: add note explaining google-api-core < 3.0.0dev pin

---

samples/snippets/subscriber.py
samples/snippets/subscriber_test.py

Fixes #<issue_number_goes_here> 🦕

Samples: Add concurrency control sample

---

samples/snippets/publisher.py
samples/snippets/requirements.txt

Fixes #<issue_number_goes_here> 🦕

feat: Add OpenTelemetry publish sample

---

samples/snippets/publisher_test.py
samples/snippets/subscriber.py

Fixes #<issue_number_goes_here> 🦕

doc: Subsribe sample
